### ISSUE TITLE
搜索时报错

### ISSUE THREAD

**Issue by isafe123** [nanshihui/Scan-T#8]
WARNING:elasticsearch:GET /datap/snifferdata/_search [status:404 request:0.015s] 
ERROR:django.request:Internal Server Error: /search/searchdetail/ 
Traceback (most recent call last): 
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response 
response = self.process_exception_by_middleware(e, request) 
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response 
response = wrapped_callback(request, _callback_args, *_callback_kwargs) 
File "/opt/godeye/godeye/spidermanage/fontsearch/searchroute.py", line 56, in detailpage 
print e 
File "/usr/local/lib/python2.7/dist-packages/elasticsearch/exceptions.py", line 55, in __str__ 
cause = ', %r' % self.info['error']['root_cause'][0]['reason'] 
TypeError: string indices must be integers 
[07/Jul/2016 17:42:53] "POST /search/searchdetail/ HTTP/1.1" 500 27

**Comment by nanshihui** [comment]
你的数据库全文检索 插件没弄好/
